Ventasbap2.0/src/accounts/passwords/urls.py
# accounts.passwords.urls.py 
from django.conf.urls import url
from django.contrib.auth import views as auth_views

urlpatterns  = [
        url(r'^password/change/$', 
                auth_views.PasswordChangeView.as_view(), 
                name='password_change'),
        url(r'^password/change/done/$',
                auth_views.PasswordChangeDoneView.as_view(), 
                name='password_change_done'),
        url(r'^password/reset/$', 
                auth_views.PasswordResetView.as_view(), 
                name='password_reset'),
        url(r'^password/reset/done/$', 
                auth_views.PasswordResetDoneView.as_view(), 
                name='password_reset_done'),
        url(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 
                auth_views.PasswordResetConfirmView.as_view(), 
                name='password_reset_confirm'),
        url(r'^password/reset/complete/$', 
                auth_views.PasswordResetCompleteView.as_view(), 
                name='password_reset_complete'),
]

Ventasbap2.0/src/accounts/urls.py
from django.conf.urls import url

from products.views import UserProductHistoryView
from .views import (
        AccountHomeView, 
        AccountEmailActivateView,
        UserDetailUpdateView
        )

urlpatterns = [
    url(r'^$', AccountHomeView.as_view(), name='home'),
    url(r'^details/$', UserDetailUpdateView.as_view(), name='user-update'),
    url(r'history/products/$', UserProductHistoryView.as_view(), name='user-product-history'),
    url(r'^email/confirm/(?P<key>[0-9A-Za-z]+)/$', 
            AccountEmailActivateView.as_view(), 
            name='email-activate'),
    url(r'^email/resend-activation/$', 
            AccountEmailActivateView.as_view(), 
            name='resend-activation'),
]

# account/email/confirm/asdfads/ -> activation view

Ventasbap2.0/src/carts/urls.py
from django.conf.urls import url

from .views import (
        cart_home, 
        cart_update, 
        checkout_home,
        checkout_done_view
        )

urlpatterns = [
    url(r'^$', cart_home, name='home'),
    url(r'^checkout/success/$', checkout_done_view, name='success'),
    url(r'^checkout/$', checkout_home, name='checkout'),
    url(r'^update/$', cart_update, name='update'),
]

Ventasbap2.0/src/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView, RedirectView


from accounts.views import LoginView, RegisterView
from addresses.views import (
    AddressCreateView,
    AddressListView,
    AddressUpdateView,
    checkout_address_create_view, 
    checkout_address_reuse_view
    )
from analytics.views import SalesView, SalesAjaxView
from billing.views import payment_method_view, payment_method_createview
from carts.views import cart_detail_api_view
from marketing.views import MarketingPreferenceUpdateView, MailchimpWebhookView
from orders.views import LibraryView

from .views import home_page, about_page, contact_page, faq_page

urlpatterns = [
    url(r'^$', home_page, name='home'),
    url(r'^about/$', about_page, name='about'),
    #url(r'^accounts/login/$', RedirectView.as_view(url='/login')),
    url(r'^accounts/$', RedirectView.as_view(url='/account')),
    url(r'^account/', include("accounts.urls", namespace='account')),
    url(r'^accounts/', include("accounts.passwords.urls")),
    url(r'^address/$', RedirectView.as_view(url='/addresses')),
    url(r'^addresses/$', AddressListView.as_view(), name='addresses'),
    url(r'^addresses/create/$', AddressCreateView.as_view(), name='address-create'),
    url(r'^addresses/(?P<pk>\d+)/$', AddressUpdateView.as_view(), name='address-update'),
    url(r'^analytics/sales/$', SalesView.as_view(), name='sales-analytics'),
    url(r'^analytics/sales/data/$', SalesAjaxView.as_view(), name='sales-analytics-data'),
    url(r'^contact/$', contact_page, name='contact'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^checkout/address/create/$', checkout_address_create_view, name='checkout_address_create'),
    url(r'^checkout/address/reuse/$', checkout_address_reuse_view, name='checkout_address_reuse'),

    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^api/cart/$', cart_detail_api_view, name='api-cart'),
    url(r'^cart/', include("carts.urls", namespace='cart')),
    url(r'^billing/payment-method/$', payment_method_view, name='billing-payment-method'),
    url(r'^billing/payment-method/create/$', payment_method_createview, name='billing-payment-method-endpoint'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^bootstrap/$', TemplateView.as_view(template_name='bootstrap/example.html')),
    url(r'^library/$', LibraryView.as_view(), name='library'),
    url(r'^orders/', include("orders.urls", namespace='orders')),
    url(r'^products/', include("products.urls", namespace='products')),
    url(r'^search/', include("search.urls", namespace='search')),
    url(r'^settings/$', RedirectView.as_view(url='/account')),
    url(r'^settings/email/$', MarketingPreferenceUpdateView.as_view(), name='marketing-pref'),
    url(r'^webhooks/mailchimp/$', MailchimpWebhookView.as_view(), name='webhooks-mailchimp'),
    url(r'^admin/', admin.site.urls),
    url(r'^faq/$', faq_page, name='faq'),

]


if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Ventasbap2.0/src/orders/urls.py
from django.conf.urls import url

from .views import (
        OrderListView, 
        OrderDetailView,
        VerifyOwnership
        )

urlpatterns = [
    url(r'^$', OrderListView.as_view(), name='list'),
    url(r'^endpoint/verify/ownership/$', VerifyOwnership.as_view(), name='verify-ownership'),
    url(r'^(?P<order_id>[0-9A-Za-z]+)/$', OrderDetailView.as_view(), name='detail'),
]

Ventasbap2.0/src/accounts/views.py
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, FormView, DetailView, View, UpdateView
from django.views.generic.edit import FormMixin
from django.http import HttpResponse
from django.shortcuts import render,redirect
from django.utils.http import is_safe_url
from django.utils.safestring import mark_safe

from ecommerce.mixins import NextUrlMixin, RequestFormAttachMixin
from .forms import LoginForm, RegisterForm,  ReactivateEmailForm, UserDetailChangeForm
from .models import EmailActivation
from .signals import user_logged_in


# @login_required # /accounts/login/?next=/some/path/
# def account_home_view(request):
#     return render(request, "accounts/home.html", {})


#LoginRequiredMixin,
class AccountHomeView(LoginRequiredMixin, DetailView):
    template_name = 'accounts/home.html'
    def get_object(self):
        return self.request.user



class AccountEmailActivateView(FormMixin, View):
    success_url = '/login/'
    form_class = ReactivateEmailForm
    key = None
    def get(self, request, key=None, *args, **kwargs):
        self.key = key
        if key is not None:
            qs = EmailActivation.objects.filter(key__iexact=key)
            confirm_qs = qs.confirmable()
            if confirm_qs.count() == 1:
                obj = confirm_qs.first()
                obj.activate()
                messages.success(request, "Your email has been confirmed. Please login.")
                return redirect("login")
            else:
                activated_qs = qs.filter(activated=True)
                if activated_qs.exists():
                    reset_link = reverse("password_reset")
                    msg = """Your email has already been confirmed
                    Do you need to <a href="{link}">reset your password</a>?
                    """.format(link=reset_link)
                    messages.success(request, mark_safe(msg))
                    return redirect("login") 
        context = {'form': self.get_form(),'key': key}
        return render(request, 'registration/activation-error.html', context)

    def post(self, request, *args, **kwargs):
        # create form to receive an email
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        msg = """Activation link sent, please check your email."""
        request = self.request
        messages.success(request, msg)
        email = form.cleaned_data.get("email")
        obj = EmailActivation.objects.email_exists(email).first()
        user = obj.user 
        new_activation = EmailActivation.objects.create(user=user, email=email)
        new_activation.send_activation()
        return super(AccountEmailActivateView, self).form_valid(form)

    def form_invalid(self, form):
        context = {'form': form, "key": self.key }
        return render(self.request, 'registration/activation-error.html', context)




class LoginView(NextUrlMixin, RequestFormAttachMixin, FormView):
    form_class = LoginForm
    success_url = '/'
    template_name = 'accounts/login.html'
    default_next = '/'

    def form_valid(self, form):
        next_path = self.get_next_url()
        return redirect(next_path)




class RegisterView(CreateView):
    form_class = RegisterForm
    template_name = 'accounts/register.html'
    success_url = '/login/'




class UserDetailUpdateView(LoginRequiredMixin, UpdateView):
    form_class = UserDetailChangeForm
    template_name = 'accounts/detail-update-view.html'

    def get_object(self):
        return self.request.user

    def get_context_data(self, *args, **kwargs):
        context = super(UserDetailUpdateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Change Your Account Details'
        return context

    def get_success_url(self):
        return reverse("account:home")


# def login_page(request):
#     form = LoginForm(request.POST or None)
#     context = {
#         "form": form
#     }
#     next_ = request.GET.get('next')
#     next_post = request.POST.get('next')
#     redirect_path = next_ or next_post or None
#     if form.is_valid():
#         username  = form.cleaned_data.get("username")
#         password  = form.cleaned_data.get("password")
#         user = authenticate(request, username=username, password=password)
#         if user is not None:
#             login(request, user)
#             try:
#                 del request.session['guest_email_id']
#             except:
#                 pass
#             if is_safe_url(redirect_path, request.get_host()):
#                 return redirect(redirect_path)
#             else:
#                 return redirect("/")
#         else:
#             # Return an 'invalid login' error message.
#             print("Error")
#     return render(request, "accounts/login.html", context)

# User = get_user_model()
# def register_page(request):
#     form = RegisterForm(request.POST or None)
#     context = {
#         "form": form
#     }
#     if form.is_valid():
#         form.save()
#     return render(request, "accounts/register.html", context)

Ventasbap2.0/src/accounts/templates/accounts/detail-update-view.html
{% extends "base.html" %}

{% block content %}
<div class='col-12 col-md-6 mx-auto'>
{% if title %}<h1 class='my-3'>{{ title }}</h1>{% endif %}
<form method='POST' action='{% if action_url %}{{ action_url }}{% endif %}'> {% csrf_token %}
    {% if next_url %}
    <input type='hidden' name='next' value='{{ next_url }}' />
    {% endif %}
  {{ form.as_p }}
  <button type='submit' class='btn btn-default my-3'>Guardar</button>
  <a href='{% url "password_change" %}'>Cambiar contraseña</a>
</form>
</div>
{% endblock %}

Ventasbap2.0/src/accounts/templates/accounts/home.html
{% extends "base.html" %}

{% load static %}

{% block title %}<title>Perfil</title>{% endblock %}


{% block base_head %}
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet" href="{% static 'assets/demo.css' %}">
  <link rel="stylesheet" href="{% static 'assets/sidebar-collapse.css' %}">

  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
  <link href='http://fonts.googleapis.com/css?family=Cookie' rel='stylesheet' type='text/css'>

{% endblock %}


{% block content %}

<aside class="sidebar-left-collapse">

    <a href="{% url 'home' %}"><img src="{% static 'img/Logo1.png' %} " width="120" height="120"></a>

    <div class="sidebar-links">

      <div class="link-yellow">

        <a href="#">
          <i class="fa fa-user"></i>Detalles de la Cuenta
        </a>

        <ul class="sub-links">
          <li><a href="{% url 'account:user-update' %}">Actualizar Datos</a></li>
          <li><a href="{% url 'password_change' %}">Cambiar contraseña</a></li>
          <li><a href="{% url 'library' %}">Biblioteca de compras</a></li>
        </ul>

      </div>

      <div class="link-red">

        <a href="#">
          <i class="fa fa-truck"></i>Compras
        </a>

        <ul class="sub-links">
          <li><a href="{% url 'orders:list' %}">Ordénes de Compra</a></li>
          <li><a href="{% url 'billing-payment-method' %}">Métodos de Pago</a></li>
          <li><a href="{% url 'addresses' %}">Direcciones para envíos</a></li>
        </ul>

      </div>

      <div class="link-green">

        <a href="#">
          <i class="fa fa-book"></i>Historial
        </a>

        <ul class="sub-links">
          <li><a href="{% url 'account:user-product-history' %}">Productos</a></li>

        </ul>

      </div>

      <div class="link-blue">

        <a href="#">
          <i class="fa fa-comments"></i>Soporte
        </a>

        <ul class="sub-links">
          <li><a href="{% url 'about' %}">Acerca de nosotros</a></li>
          <li><a href="{% url 'contact' %}">Contáctanos</a></li>
        </ul>

      </div>

    </div>

  </aside>
<center>
  <div class="main-content">

    <div class="menu">

      <img class="arrow left" src="{% static 'assets/images/demo-arrow-left.png' %}" alt="arrow" height="120">
    
      <strong><h1 style="color: black">Ventasbap</h1></strong>
      <p align="justify">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc </p>


    </div>

  </div>
</center>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <script>

    $(function () {

      var links = $('.sidebar-links > div');

      links.on('click', function () {

        links.removeClass('selected');
        $(this).addClass('selected');

      });
    });

  </script>

{% endblock %}

Ventasbap2.0/src/accounts/templates/accounts/login.html
{% extends "base.html" %}

{% load static %}

{% block title %}<title>Inicia Sesión</title>{% endblock %}


{% block base_head %}


	<!--modificar etiquetas ///////////////////////// -->

	<!-- Meta tag Keywords -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="Portrait Login Form Responsive Widget,Login form widgets, Sign up Web forms , Login signup Responsive web form,Flat Pricing table,Flat Drop downs,Registration Forms,News letter Forms,Elements"
	/>
	<script>
		addEventListener("load", function () {
			setTimeout(hideURLbar, 0);
		}, false);

		function hideURLbar() {
			window.scrollTo(0, 1);
		}
	</script>
	<!-- Meta tag Keywords -->
	<!-- css files -->
	<link rel="stylesheet" href="{% static 'css/Login_style.css' %}" type="text/css" media="all" />
	<!-- Style-CSS -->
	<link rel="stylesheet" href="{% static 'css/Login.css' %}">
	<!-- Font-Awesome-Icons-CSS -->
	<!-- //css files -->
	<!-- online-fonts -->

	<!-- Carpeta fonts?//////////////////////////////// -->	
	<link href="//fonts.googleapis.com/css?family=Tangerine:400,700" rel="stylesheet">
	<link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">
	<!-- //online-fonts -->
{% endblock %}


{% block content %}
<div class="main-content-agile">
		<div class="sub-main-w3">
			<img src="{% static 'img/Logo1.png' %}" width="120" height="120" alt="" />
			<p> <br> </p>
			<form action="#" method="post">
  			{% csrf_token %}
  			{{ form.non_field_errors }}

				<div class="pom-agile">
					<span class="fa fa-user-o" aria-hidden="true"></span>
					<input placeholder="Email" name="email" class="user" type="text" required="">
					<div class="forgot-w3l">
						{{ form.email.errors}}
					</div>
				</div>
				<div class="pom-agile">
					<span class="fa fa-key" aria-hidden="true"></span>
					<input placeholder="Contraseña" name="password" class="pass" type="password" required="">
					<div class="forgot-w3l">
						{{ form.password.errors}}
					</div>
				</div>
				<div class="sub-w3l">
					<div class="sub-agile">
						<input type="checkbox" id="brand1" value="">
						<label for="brand1">
							<span></span>Recuérdame</label>
					</div>
					<div class="clear"></div>
				</div>
				<div class="right-w3l">
					<input name="login" type="submit" value="INICIA SESIÓN">
				</div>
				<div class="forgot-w3l">
					<a href="#">¿Olvidaste tu Contraseña?</a>
				</div>
				<div class="forgot-w3l">
					<a href="{% url 'home' %}">Inicio</a>|
					<a href="{%url 'register' %}">Registrate</a>
				</div>
			</form>
		</div>
	</div>
	<!--//main-->
	<!--footer-->
	<div class="footer">
		<p>&copy; 2018 Diseñado Por
			<a href="http://w3layouts.com">W3layouts</a> | Modificado Por VentasBap
		</p>
	</div>

{% endblock %}

Ventasbap2.0/src/accounts/templates/accounts/register.html
{% extends "base.html" %}

{% block title %}<title>Registrate</title>{% endblock %}

{% load static %}

{% block base_head%}

<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="Music School Registration Responsive, Login form web template,Flat Pricing tables,Flat Drop downs  Sign up Web Templates, Flat Web Templates, Login signup Responsive web template, Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design"
	/>
	<script type="application/x-javascript">
		addEventListener("load", function () {
			setTimeout(hideURLbar, 0);
		}, false);

		function hideURLbar() {
			window.scrollTo(0, 1);
		}
	</script>

	<!-- fonts -->
	<link href="//fonts.googleapis.com/css?family=Tangerine:400,700" rel="stylesheet">
	<link href="//fonts.googleapis.com/css?family=Hind+Siliguri:300,400,500,600,700&amp;subset=bengali,latin-ext" rel="stylesheet">

	<!-- /fonts -->

	<!-- css -->
	<link href="{% static 'css/Registrate_style.css' %}" rel="stylesheet" type='text/css' media="all" />
	<!-- /css -->


{% endblock %}


{% block content %}

     <!--<h1>Register</h1>
    <form method='POST'> {% csrf_token %}
      {{ form }}
      <button type='submit' class='btn btn-default'>Submit</button>
    </form>-->

 
    <h1 class="w3layouts">¡Sé parte de los clientes <BR> de VentasBap! </h1>
	<div class="clear"></div>
	<div class="content-w3ls">

		<div class="form_w3layouts">
			<form method="post" class="agile_form" id="register">
  			{% csrf_token %}
  			{{ signup_form.non_field_errors }}

  				<ul>
					<li>-Todos los campos son obligatorios</li>
					<li>-Longitud mínima para la contraseña: 8 caracteres</li>
				</ul>
				<br>

				<div class="agileits-left">
					<input type="text" name="full_name" class="name" placeholder="Nombre y Apellido" required="" oninvalid="this.setCustomValidity('Este Campo es obligatorio')" oninput="setCustomValidity('')">
					{{ form.full_name.errors }}
					
				</div>
				
				<div class="agileits-left">
					<input type="text" name="ci" class="Id" placeholder="Cédula de Identidad" required="" oninvalid="this.setCustomValidity('Este Campo es obligatorio')" oninput="setCustomValidity('')">
					{{ form.ci.errors }}
					
				</div>
				<div class="agileits-left">
					<input type="text" name="sex" class="gender" placeholder="Género" required="" oninvalid="this.setCustomValidity('Este Campo es obligatorio')" oninput="setCustomValidity('')">
					{{ form.sex.errors }}
					
				</div><!--
				<div class="checkin agileits-left">
					<input placeholder="Fecha de Nacimiento" class="Bdate" name="Bdate" id="datepicker" type="text" value="" onfocus="this.value = '';"
					    onblur="if (this.value == '') {this.value = '';}" required="" />
					{% if form.Bdate.errors %}
						<h1>error Bdate</h1>
					{% endif %}
				</div>-->
				<div class="agileits-left s2-w3ls">
					<input type="text" name="bday" class="cellphone" placeholder="Fecha de Nacimiento (AAAA-MM-DD)" required="" oninvalid="this.setCustomValidity('Este Campo es obligatorio')" oninput="setCustomValidity('')">
					{{ form.bday.errors }}
					
				</div>
				<div class="agileits-left s2-w3ls">
					<input type="text" name="cellphone" class="cellphone" placeholder="Número de Teléfono Móvil" required="" oninvalid="this.setCustomValidity('Este Campo es obligatorio')" oninput="setCustomValidity('')">
					{{ form.cellphone.errors }}
					
				</div>
				<div class="agileits-left">
					<input type="text" name="city" class="City" placeholder="Ciudad Donde Vive" required="" oninvalid="this.setCustomValidity('Este Campo es obligatorio')" oninput="setCustomValidity('')">
					{{ form.city.errors }}
					
				</div>
				<div class="agileits-left">
					<input type="email" name="email" class="email" placeholder="Correo Electrónico" required="" oninvalid="this.setCustomValidity('Este Campo es obligatorio')" oninput="setCustomValidity('')">
					{{ form.email.errors }}
				</div>
				<!--<div class="agileits-left">
					<input type="text" name="name" class="username" placeholder="Dirección de Envío" required="">
				</div>-->
				<br>
				<div class="agileits-left">
					<input type="password" name="password1" class="password" placeholder="Contraseña" required="" oninvalid="this.setCustomValidity('Este Campo es obligatorio')" oninput="setCustomValidity('')">
					{{ form.password1.errors }}
					
				</div>
				<div class="agileits-left">
					<input type="password" name="password2" class="password" placeholder="Confirmación de contraseña" required="" oninvalid="this.setCustomValidity('Este Campo es obligatorio')" oninput="setCustomValidity('')">
					{{ form.password2.errors }}
					
				</div>
				
				<div class="submit-w3l">
					<input name="register" type="submit" value="REGISTRATE">
				</div>
			</form>
			<br>
			<center>
					<div>

         			{% if request.user.is_authenticated %}
						<a href="{% url 'home' %}"><font color="black">Inicio</font></a>
					{% else %}
						<a href="{% url 'home' %}"><font color="black">Inicio</font></a> |
						<a href="{%url 'login' %}"><font color="black">Iniciar Sesión</font></a>
					{% endif %}
					</div>
			</center>
		</div>
		<div class="clear"></div>
	</div>
	<div class="clear"></div>
	<h2 class="copyright-agileits">© 2018 Music School Registration. Diseñado por w3layouts | Modificado por VentasBap
	</h2>
	<!--<div class="clear"></div>-->
	<!-- js -->
	
	<!--<script src="{% static 'js/Registrate_jquery-2.2.3.min.js' %}"></script>-->
	<!-- //js -->
	<!-- date-->
	<!--<link rel="stylesheet" href="{% static 'css/Registrate_jquery-ui.css' %}" />
	<script src="{% static 'js/Registrate_jquery-ui.js' %"></script>
	<script>
		$(function () {
			$("#datepicker,#datepicker1").datepicker();
		});
	</script>-->
	<!-- //date -->
	<!-- time -->
	<!--<script type="text/javascript" src="[% static 'js/Registrate_wickedpicker.js' %}"></script>
	<script type="text/javascript">
		$('.timepicker').wickedpicker({
			twentyFour: false
		});
	</script>
	<link href="{% static 'css/Registrate_wickedpicker.css' %" rel="stylesheet" type='text/css' media="all" />-->
	<!-- //time -->


  <!--<h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>-->


{% endblock %}